---
- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: cria arquivo de logrotate para os containers docker
  copy: src=logrotate-docker-containers dest=/etc/logrotate.d/docker-container

- name: expoe as variaveis docker_bridge_ip e docker_bridge_cidr
  set_fact: docker_bridge_ip="{{ docker_bridge_ip }}" docker_bridge_cidr="{{ docker_bridge_cidr }}"
