---
- name: registra o repositório yum oficial do docker
  copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo owner=root group=root mode=0644

- name: instala o docker
  yum: name=docker-engine state=present

- name: garante a existência da pasta /opt/docker
  file: dest=/opt/docker state=directory

- name: link simbolico para docker
  file: dest=/var/lib/docker src=/opt/docker state=link

- name: grupo docker
  group: name=docker state=present

- name: usuario inovapar no grupo docker
  user: name=inovapar groups=docker append=yes

- name: inicializa e habilita docker
  service: name=docker state=started enabled=yes

# dependência para recuperar os manifests das imagens, usado depois também pelo app-state
- name: instala python-httplib2
  yum: name=python-httplib2 state=present
