---
dependencies:
  - role: centos66
    when: ansible_distribution == 'CentOS' and
      (ansible_distribution_version == "6.4" or ansible_distribution_version == "6.5" or ansible_distribution_version == "6.6")